import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import todos from '@/data/todos.json'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Animus | Prueba Técnica React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.sideBar}>
          <h1>Animus ToDos</h1>
        </div>
        <div className={styles.content}>
          {todos.map((todo) => {
            return (
              <div key={todo.id} className={styles.todo}>
                <div className={styles.todo__status}>
                  <input type="checkbox" />
                </div>
                <div className={styles.todo__content}>
                  <p>{todo.name}</p>
                  <p>{todo.createdAt}</p>
                </div>
              </div>
            )
          })}
        </div>
      </main>
    </>
  )
}
