import Head from 'next/head'
import React from 'react'
import { Chivo } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const chivo = Chivo({ subsets: ['latin'] })

const BasePage = ({title,children}) => {
  return <>
  <Head>
    <title>Animus | {title}</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  
  <main className={`${styles.main} ${chivo.className}`}>
    {children}
  </main>
</>
}

export default BasePage